# Generated by Django 3.0.3 on 2020-07-05 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uname', models.CharField(default='', max_length=100)),
                ('bid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bname', models.CharField(default='', max_length=100)),
                ('bcontent', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
